"""empty message

Revision ID: 691950248dde
Revises: bbdba56095fe
Create Date: 2024-03-15 11:48:42.902888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691950248dde'
down_revision = 'bbdba56095fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('manager', 'tutor', 'member'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
