"""empty message

Revision ID: e6d1960fcf59
Revises: 9ba4f4707a32
Create Date: 2024-03-19 00:07:13.070061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6d1960fcf59'
down_revision = '9ba4f4707a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_column('finish_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_datetime', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('end_datetime')

    # ### end Alembic commands ###
