"""empty message

Revision ID: 945dbb7d304c
Revises: 
Create Date: 2024-03-14 21:48:08.298596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945dbb7d304c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
