"""empty message

Revision ID: 0d1843648592
Revises: cef246582726
Create Date: 2024-03-19 01:33:40.429765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d1843648592'
down_revision = 'cef246582726'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  # op.drop_table('lesson_schedule')
  # op.drop_table('workshop_schedule')
  with op.batch_alter_table('booking', schema=None) as batch_op:
    batch_op.add_column(sa.Column('schedule_id', sa.Integer()))

  op.execute('''
        UPDATE booking b
        INNER JOIN lesson_schedule ls
        ON ls.id = b.lesson_schedule_id
        INNER JOIN lesson ON lesson.id = ls.lesson_id
        INNER JOIN schedule s on s.lesson_id = lesson.id
        SET b.schedule_id = s.id
    ''')

  op.execute('''
        UPDATE booking b
        INNER JOIN workshop_schedule ws
        ON ws.id = b.workshop_schedule_id
        INNER JOIN workshop ON workshop.id = ws.workshop_id
        INNER JOIN schedule s on s.workshop_id = workshop.id
        SET b.schedule_id = s.id
    ''')

  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('booking', schema=None) as batch_op:
    batch_op.drop_column('schedule_id')

  # ### end Alembic commands ###
