"""empty message

Revision ID: 152d381f6eeb
Revises: 4f08229ed22d
Create Date: 2024-03-17 21:18:15.725875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '152d381f6eeb'
down_revision = '4f08229ed22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('lesson_number',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaching_subjects', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('introduction')
        batch_op.drop_column('qualification')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('teaching_subjects')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('lesson_number',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
