"""empty message

Revision ID: bbdba56095fe
Revises: 945dbb7d304c
Create Date: 2024-03-14 23:54:57.019170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbdba56095fe'
down_revision = '945dbb7d304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('booking_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('lession_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('profile_image_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('profile_image_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lession_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_ibfk_2', 'lesson', ['lession_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###
