"""empty message

Revision ID: c93676019c0e
Revises: 1164474491b3
Create Date: 2024-03-17 01:00:56.416634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c93676019c0e'
down_revision = '1164474491b3'
branch_labels = None
depends_on = None


def upgrade():
  op.execute('SET FOREIGN_KEY_CHECKS=0;')
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('booking', schema=None) as batch_op:
    batch_op.add_column(sa.Column('lesson_schedule_id',
                        sa.Integer(), nullable=True))
    batch_op.add_column(
        sa.Column('start_datetime', sa.DateTime(), nullable=False))
    batch_op.add_column(
        sa.Column('end_datetime', sa.DateTime(), nullable=False))
    batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
    batch_op.alter_column('confirmed',
                          existing_type=mysql.TINYINT(display_width=1),
                          nullable=False)
    batch_op.drop_constraint('booking_ibfk_4', type_='foreignkey')
    batch_op.create_foreign_key(None, 'lesson_schedule', ['lesson_schedule_id'], [
                                'id'], onupdate='CASCADE', ondelete='CASCADE')
    batch_op.drop_column('lesson_id')
    batch_op.drop_column('booking_datetime')

  with op.batch_alter_table('lesson', schema=None) as batch_op:
    batch_op.add_column(sa.Column('cost', sa.Numeric(
        precision=8, scale=2), nullable=False))

  with op.batch_alter_table('reminder', schema=None) as batch_op:
    batch_op.alter_column('receiver_id',
                          existing_type=mysql.INTEGER(),
                          nullable=False)
    batch_op.alter_column('sender_id',
                          existing_type=mysql.INTEGER(),
                          nullable=False)

  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('reminder', schema=None) as batch_op:
    batch_op.alter_column('sender_id',
                          existing_type=mysql.INTEGER(),
                          nullable=True)
    batch_op.alter_column('receiver_id',
                          existing_type=mysql.INTEGER(),
                          nullable=True)

  with op.batch_alter_table('lesson', schema=None) as batch_op:
    batch_op.drop_column('cost')

  with op.batch_alter_table('booking', schema=None) as batch_op:
    batch_op.add_column(sa.Column('booking_datetime',
                        mysql.DATETIME(), nullable=True))
    batch_op.add_column(
        sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    batch_op.drop_constraint(None, type_='foreignkey')
    batch_op.create_foreign_key('booking_ibfk_4', 'lesson', ['lesson_id'], [
                                'id'], onupdate='CASCADE', ondelete='CASCADE')
    batch_op.alter_column('confirmed',
                          existing_type=mysql.TINYINT(display_width=1),
                          nullable=True)
    batch_op.drop_column('created_at')
    batch_op.drop_column('end_datetime')
    batch_op.drop_column('start_datetime')
    batch_op.drop_column('lesson_schedule_id')

  # ### end Alembic commands ###
