"""empty message

Revision ID: 9de6d92ea078
Revises: 99a885ccd447
Create Date: 2024-03-23 23:56:15.845262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision = '9de6d92ea078'
down_revision = '99a885ccd447'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('payment',
                  sa.Column('id', sa.Integer(),
                            autoincrement=True, nullable=False),
                  sa.Column('first_name', sa.String(
                      length=32), nullable=False),
                  sa.Column('last_name', sa.String(length=32), nullable=False),
                  sa.Column('email', sa.String(length=255), nullable=True),
                  sa.Column('address', sa.String(length=255), nullable=True),
                  sa.Column('address2', sa.String(length=255), nullable=True),
                  sa.Column('country', sa.String(length=64), nullable=True),
                  sa.Column('state', sa.String(length=64), nullable=True),
                  sa.Column('suburb', sa.String(length=64), nullable=True),
                  sa.Column('postcode', sa.String(length=32), nullable=True),
                  sa.Column('paid_at', sa.DateTime(), nullable=False,
                            server_default=sa.func.now()),
                  sa.Column('status', sa.String(length=64), nullable=False),
                  sa.Column('payment_type', sa.String(
                      length=64), nullable=True),
                  sa.Column('name_on_card', sa.String(
                      length=255), nullable=False),
                  sa.Column('card_number', sa.String(
                      length=4), nullable=False),
                  sa.Column('expiration_date', sa.String(
                      length=25), nullable=True),
                  sa.Column('user_id', sa.Integer(), nullable=True),
                  sa.Column('subscription_id', sa.Integer(), nullable=True),
                  sa.Column('booking_id', sa.Integer(), nullable=True),
                  sa.ForeignKeyConstraint(
                      ['booking_id'], ['booking.id'], onupdate='CASCADE', ondelete='CASCADE'),
                  sa.ForeignKeyConstraint(['subscription_id'], [
                      'subscription.id'], onupdate='CASCADE', ondelete='CASCADE'),
                  sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                          onupdate='CASCADE', ondelete='CASCADE'),
                  sa.PrimaryKeyConstraint('id')
                  )

  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###

  op.drop_table('payment')
  # ### end Alembic commands ###
