"""empty message

Revision ID: a417abf9e220
Revises: 691950248dde
Create Date: 2024-03-15 12:14:04.331595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a417abf9e220'
down_revision = '691950248dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=8, scale=2), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=8, scale=2), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
